image:
  repository: artifactory.dagility.com/docker/vdchdeploy-backend
  tag: latest
  pullPolicy: Always
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-internal
  hosts:
  - host: vdchdeploy-backend-cattle-impersonation-system.dagility.com
    paths:
    - /
serviceAccount:
  create: false
