image:
  repository: registry.ustpace.com/docker-sandbox/vdchdeploy-backend
  tag: latest
  pullPolicy: Always
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-internal
  hosts:
  - host: vdchdeploy-backend-edgeops-keycloak.dagility.com
    paths:
    - /
serviceAccount:
  create: false
